version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-chatbot-backend
    restart: always
    expose:
      - "8000"
    environment:
      - APP_NAME=local-chatbot
    volumes:
      - ./backend:/app/backend  # Optional for development
    networks:
      - chatbot-network

  nginx:
    image: nginx:stable-alpine
    container_name: local-chatbot-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/static:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
